### ISSUE TITLE
[Feature Request] replace the gross X logo with the Og Twitter one

### ISSUE THREAD

**Issue by FemboyLoverSquad** [stevencaiOR/stevencaiOR.github.io#1]
This is a request to replace the X logo with the Twitter one. I mean it's going to be call 'twitter' then might as well actually use use the correct one 

this is for 
`https://raw.githubusercontent.com/stevencaiOR/stevencaiOR.github.io/refs/heads/main/discord-themes/add-ons/better-social-links.css`

![Capt452424ure](https://github.com/user-attachments/assets/18840dc4-a81f-4a73-9a4d-6702079a55d1)

**Comment by FemboyLoverSquad** [comment]
nvm learn how to do it my self
```css
[d="M13.86 10.47 21.15 2h-1.73l-6.33 7.35L8.04 2H2.22l7.64 11.12L2.22 22h1.72l6.68-7.77L15.96 22h5.82l-7.92-11.53Zm-2.36 2.75-.78-1.11L4.57 3.3h2.65l4.97 7.11.77 1.1 6.46 9.25h-2.65l-5.27-7.54Z"] {
  d: path("m20.75 7.51.01.59c0 5.96-4.54 12.84-12.84 12.84-2.45 0-4.86-.7-6.92-2.03a9.06 9.06 0 0 0 6.68-1.87 4.52 4.52 0 0 1-4.22-3.13c.68.13 1.38.1 2.04-.08A4.51 4.51 0 0 1 1.88 9.4v-.05c.63.35 1.33.54 2.05.56a4.52 4.52 0 0 1-1.4-6.02 12.81 12.81 0 0 0 9.3 4.71 4.52 4.52 0 0 1 7.7-4.12 9.06 9.06 0 0 0 2.86-1.1 4.53 4.53 0 0 1-1.98 2.5c.9-.1 1.77-.34 2.59-.7-.6.9-1.37 1.7-2.25 2.33Z");
}
```
